### ISSUE TITLE
How to unpickle when receiving a Python pickled stream 

### ISSUE THREAD

**Issue by pavan4** [hydrogen18/stalecucumber#14]
I have my tcp server in golang and would like to receive and decode a pickled stream

The python side roughly looks like this 
``` 
sock = socket(AF_INET,SOCK_STREAM)
sock.connect(('127.0.0.1',5006))
sock.send(cPickle.dumps(data))
```

The Go server looks like this: 
```
ln, _ := net.Listen(CONN_TYPE, CONN_PORT)
conn, _ := ln.Accept()
data := make([]byte,0)
for {
    // for gob I would normally do this
    //  dec.Decode(&data); 
    err := stalecucumber.UnpackInto(&data).From(stalecucumber.Unpickle(<can't provide conn here>))
}
```
Any way to listen to a stream of pickled objects and decode them ?

**Comment by hydrogen18** [comment]
Why can't you call `stalecucumber.Unpickle(conn)` ? What happens if you do that? Also, what is `data` in the python code?

**Comment by pavan4** [comment]
I am sending a byte stream and data contains it.

If I use `conn` I raise an error which says - ` error unpacking byte stream`

**Comment by hydrogen18** [comment]
So `data` in your python code is a string or something like that?

**Comment by pavan4** [comment]
`data` is a byte array

**Comment by hydrogen18** [comment]
I don't think you're getting an error of "error unpacking byte stream" from my library. More likely than not, the target type in the Go code does not agree with what is encoded by the `cPickle` module in python.

Python does not really support byte arrays, most people just use a string. Trying to send a byte array (really a string in python) over a socket is an unusual use case for any language. You generally do not need a serialization protocol to send a byte array, just the socket alone can do that.

Some remarks

1. Calling `cPickle.dump` or `pickle.dump` without the protocol argument uses the original protocol version 0. This protocol is basically broken. It is much better to do `cPickle.dump(data, 2)` to use the newer protocol version.
2. For small data, you can use the `pickletools` module to look at the data on the wire. For example `pickletools.dis(cPickle.dumps(r'foobar',2))` shows this

```
    0: \x80 PROTO      2
    2: U    SHORT_BINSTRING 'foobar'
   10: q    BINPUT     1
   12: .    STOP
highest protocol among opcodes = 2
```

Although I have specified a value of `r'foobar'` in python, it gets transmitted as a string by the pickle protocol. As a result, you would need to use a string type as the destination for the value in the go code.

**Comment by hydrogen18** [comment]
Closed due to lack of response.
