### ISSUE TITLE
Pickle Unsupported version #4

### ISSUE THREAD

**Issue by xenu256** [hydrogen18/stalecucumber#15]
```text
Pickle Machine failed on opcode:0x80. Stack size:0. Memo size:0. Cause:Unsupported version #4 detected
```

**Comment by hydrogen18** [comment]
Can you please provide an example of the code you are using to generate this pickled data?

**Comment by xenu256** [comment]
OK, here it is, struct truncated to reflect only data types, it's pandas pickled file:

```go
type SystemModel struct {
	A string
	B       float64
	C int
}

data, err := ioutil.ReadFile(dataFile)
		if err != nil {
			log.Fatal(err)
		}

systemModel := models.SystemModel{}
		d := bytes.NewReader(data)
		err = stalecucumber.UnpackInto(&systemModel).From(stalecucumber.Unpickle(d))
		if err != nil {
			log.Fatal(err)
		}
```

**Comment by hydrogen18** [comment]
That looks like the code you are using to (attempt) to read the data in Go.

I meant the python code that writes the data.

**Comment by xenu256** [comment]
Basically it can be recreated with:

```python
from pandas import DataFrame

a = ["2017-01-01", "2017-01-02", "2017-01-03"]
b = [100.1, 100.2, 100.3]
c = [1, 2, 3]

data = {"A": a, "B": b, "C": c}
df = DataFrame(data)
df.to_pickle("df.pckl")
````

**Comment by hydrogen18** [comment]
It looks like you are using Python 3 with pandas. The pickle format is described as a series of protocols, where protocol 2 contains all of protocol 0, protocol 1, and some new features.

Python 3 implements this additional PEP to describe protocol number 3
https://www.python.org/dev/peps/pep-3154/

The pandas library prefers to use the highest protocol version available (which is good). But when running on Python 3 this library cannot read the highest protocol.

You can work around this by doing the following in your python code

```
df.to_pickle("df.pckl", protocol = 2)
```

This will use protocol 2 which this library should be able to read. 

Protocol 3 actually only adds 10 opcodes (which would become 10 or so functions in this library), so it would not be hard to add support for. However, I don't really have the time to work on it.

**Comment by xenu256** [comment]
I see, didn't used protocol 2 long ago... Thank you.
