### ISSUE TITLE
support for unpickling object instances?

### ISSUE THREAD

**Issue by trtg** [hydrogen18/stalecucumber#16]
The comments on pickle_machine.go suggest that a future revision of the library would allow for at least partial support of unpickling object instances. Was a branch ever created to work on this? I don't see one here, but wasn't sure if maybe it was just never pushed up to github.

**Comment by hydrogen18** [comment]
It's possible, I just haven't ever gotten enough feedback from anyone interested to build something useful

**Comment by hydrogen18** [comment]
Do you want to try and contribute a use case for this functionality? It should be a brief description of what you are aiming to achieve and what functionality would make that possible.

**Comment by hydrogen18** [comment]
Support for this has been added. Please review the documentation and reopen if you can't get it to work
