### ISSUE TITLE
pickled list of numbers can not be unpacked into []int64 or []float64 

### ISSUE THREAD

**Issue by willauld** [hydrogen18/stalecucumber#17]
I have a list of numbers in python that I am pickling. It is a list of real numbers but many are zero. I get the following errors:
Error unpacking 0(int64) into 0(float64):Target type does not match source type
and if I change the my target to int64 I get:
Error unpacking 0(float64) into 0(int64):Target type does not match source type

It seems like the library should be able to do the right thing here and match what python is doing. What do you think?
Thanks,
Will

**Comment by hydrogen18** [comment]
This should be straightforward enough to deal with, 0 can be handled as a special case. I'll follow up on this soon.

**Comment by hydrogen18** [comment]
I haven't forgotten about this, work has just been occupying 101% of my effort recently.

**Comment by willauld** [comment]
Thanks, I understand completely.

 

Will

**Comment by hydrogen18** [comment]
I'm just now getting around to looking at this. Have you tried unpacking into a destination type of `[]interface{}` ? You would need to iterate over it and check for `float64`/`int64` as necessary in your code. 

There are test cases in the existing library that handle inputs of python lists with mixed types already. So I'm assuming you could unpack into `[]interface{}` without issue.

**Comment by willauld** [comment]
If I have to go through and convert the data after loading then pickle isn't doing its job and I can write specific functions to load and store the data. Using pickle in python and gob in go is very nice and pretty straightforward. I thought that using pickle to pass several large float64 arrays would make the transition from python to go pretty effortless but if it is not and specific code is needed to convert then it is better just to write the needed code. I ended up writing the arrays out in binary and reading them in in the same way. This does the job needed but wasn't as nice as when the library does the heavy work.

**Comment by hydrogen18** [comment]
I don't think there is anything more I can do to help on this issue
