### ISSUE TITLE
pickled objects, 0x63 strikes again

### ISSUE THREAD

**Issue by epim** [hydrogen18/stalecucumber#18]
Howdy!

I've seen a couple other issues opened where you requested a use case to support pickled objects, so I'm opening this issue to provide one.

I'm hitting the opcode 0x63 error when trying to unpickle /var/lib/cloud/instance/obj.pkl, which is the data file for cloud-init. Cloud-init is something that runs on boot for instances created by popular cloud platforms such as Amazon EC2 and OpenStack. In my case I have a tool (written in go) that needs to grab certain metadata values out of that file on every instance that we boot. 

the code and the error:

`package main

import (
	"github.com/hydrogen18/stalecucumber"
	"os"
	"fmt"
)

func getPickleData() string {
	pickleFile := "/var/lib/cloud/instance/obj.pkl"
	data, err := os.Open(pickleFile)
	if err != nil {
		fmt.Printf("Failed to read %s: %s\n", pickleFile, err)
		os.Exit(1)
	}
	_, err = stalecucumber.Unpickle(data)
	if err != nil {
		fmt.Printf("Failed to unpickle: %s\n",err)
		os.Exit(1)
	}

	return "not reached"
}

func main() {
	_ = getPickleData()
}`

fails reading a pickled object, returning:

`$ sudo ./main
Failed to unpickle: Pickle Machine failed on opcode:0x63. Stack size:0. Memo size:0. Cause:Input encountered opcode that is not implemented`

**Comment by hydrogen18** [comment]
Can I get an example of one these cloud init pickle files from somewhere?

**Comment by hydrogen18** [comment]
Support for this has been added. Please review the documentation and reopen if you can't get it to work
