### ISSUE TITLE
Unpickle "set" support

### ISSUE THREAD

**Issue by grooveygr** [hydrogen18/stalecucumber#19]
Set is a popular data structure used in python and quite often it is pickled/unpickled when storing state.
The pickle spec does not specifically address sets, but provides a way of serializing them as a class (which is currently not supported by stalecucmber).

I have a pull request coming up to specifically address sets. Far from a generalized solution to class serialization, but quite useful IMHO!

**Comment by hydrogen18** [comment]
Merged
