### ISSUE TITLE
how to select protocol

### ISSUE THREAD

**Issue by simsunny22** [hydrogen18/stalecucumber#24]
i think go pickle uses protocol version 2,
if i want use protocol 0, how can i change it?
thank you

**Comment by hydrogen18** [comment]
If this is in reference to writing, this only writes the newer protocol.

**Comment by simsunny22** [comment]
thanks,  means i need to implement pickle  protocol 0

**Comment by hydrogen18** [comment]
You could, but why? Only very old versions of Python require protocol 0. What version of python are you using?

**Comment by simsunny22** [comment]
because our py project use pickle.dumps("test"), not  use pickle.dumps("test", 2).
if you not specify version, the versioin default is 0.  
And they don not want to user pickle.dumps("test") where would effect old data in redis. 
So I need version 0, thank you bro.
