### ISSUE TITLE
How to make the return a string?

### ISSUE THREAD

**Issue by dizzythinks** [hydrogen18/stalecucumber#3]
This might be the wrong place to post this but I'm completely stuck. I've been literally doing Go for a couple of days and have been using your library to unpickle something. So far so good and I have the following, which works on a Pickle object:

    func unPickle(buf io.Reader) ([]interface{}, error) {
        unpickled, err := stalecucumber.ListOrTuple(stalecucumber.Unpickle(buf))
        return unpickled, err
    }

This is where I get stuck. I have an interfaces object returns and I'm a little confused conceptually by these. If I run the return object though the following function I get some output of the unpickled object:

    func PrintAll(unpickled []interface{}) {
         for _, val := range unpickled {
            fmt.Println(val)
        }
    }

Output:

    [foo.bar.pickle.0 [1420823013 74]]
    [foo.bar.pickle.1 [1420823013 64]]
    [foo.bar.pickle.2 [1420823013 77]]
    [foo.bar.pickle.3 [1420823013 18]]

Any tips on how I go about getting that to actually br like this though?

"foo.bar.pickle.0 1420823013 74"\n"foo.bar.pickle.1 1420823013 64"\n"foo.bar.pickle.2 1420823013 77"\n"foo.bar.pickle.3 1420823013 18"

Is there a more approriate way to use stalecucumber to achieve this? Apologies again if this is the wrong place to ask.

**Comment by hydrogen18** [comment]
It sounds like you want to use `fmt.Printf` to format the output. Since you have nested lists that is non trivial. I suggest posting the question on StackOverflow and linking to that from here. This isn't really a place for general programming advice.

**Comment by dizzythinks** [comment]
Thanks for that, will look at that. Yes am trying to add one to carbon-relay-ng. Have got part the way there with a listener and your library but was planning on converting it back into plain text to pass it back through the route handler. Thanks again, thought I would ask here first in case I was missing some magic in the library.

**Comment by dizzythinks** [comment]
Guess this can be closed :-)

**Comment by hydrogen18** [comment]
I can probably help you add the listener you are trying to add. Email me at hydrogen18 at gmail.com
